### ISSUE TITLE
Reset / delete Gold history

### ISSUE THREAD

**Issue by Luellin** [Xruptor/xanGoldMine#1]
Hi i want to reset all my gold progression but the life time total earned is not reseted no matter what i do. is there a way to reset all the gold history?

**Comment by Xruptor** [comment]
I'm assuming you are playing on Retail servers.  That lifetime amount you cannot delete is actually from your account.  If you open the Achievement window and go to the Statistics tab.  There is a category called "Character" and under that another one called "Wealth".  It pulls the values from there.  Those are your true lifetime amounts ever gained on your account.

I could possibly put an option to turn that off and allow users to define their own lifetime amounts manually.  However those numbers wouldn't be the true lifetime amount.

Could you give me an example of what you are trying to do or accomplish?  Those lifetime accounts in the achievement window are on a per character basis.

**Comment by Xruptor** [comment]
I'll add an option to disable the Achievement Statistics Window lifetime totals.  I will also add an option to reset the gold via slash command.
