### ISSUE TITLE
Taxi costs not accumulating in Classic (And presumably TBC)

### ISSUE THREAD

**Issue by draknyte1** [Xruptor/xanGoldMine#2]
After finding all your addons the other day upon my return to classic and falling in love, I've noticed that my spending on 'Taxis' has never gone above 0 copper. I presume by Taxis it is in reference to flight paths? Pardon me if not.

I'll report back later to see if this behaviour has changed in TBC, I assume it will be the same.
But congrats on all of your addons (That I am using at least) still functioning fine as far as I can tell after 30 minutes of TBC now that Pre-Patch is done.

**Comment by Xruptor** [comment]
It should be calculating the taxi information.  Odd, it must be something related to how taxi (flightpaths) are triggered on Classic or TBC.  BTW Taxi is how Blizzard refers to flightpaths in code.  It should initiate the calculation once you take a taxi.  If it's not doing that then something else is going on.

**Comment by Xruptor** [comment]
Have not heard back on confirmation.  Closing Ticket.

**Comment by tanrak** [comment]
Hi, i have the same problem under TBC Classic. The money appears correctly under the total spent but not allocated to the taxi fares.

**Comment by Xruptor** [comment]
> Hi, i have the same problem under TBC Classic. The money appears correctly under the total spent but not allocated to the taxi fares.

So it does add it to the total money just never to the actual taxi fare spent right?  I'm assuming your taxi fair total just stays exactly the same?

**Comment by tanrak** [comment]
Attached are a few pictures (bevore flight, outbound flight, return flight) for illustration. Taxi Fares are ever "wating" respectively money=0. Session and lifetime is calculated correctly. On this occasion, I notice that "Total Diff" is the sum of "Total Earned" and "Total Spent" its. Shouldn't that be the difference?
![1](https://user-images.githubusercontent.com/35105392/141118288-3040a7e4-0fd1-47f4-bd15-fd4e5dd4e9af.jpg)
![2](https://user-images.githubusercontent.com/35105392/141118306-d04ab951-6e3c-46ef-a2da-2c3ae2c7e26b.jpg)
![3](https://user-images.githubusercontent.com/35105392/141118313-f1505fbd-4ff9-4241-8c14-b6aaea92ee87.jpg)

**Comment by Xruptor** [comment]
Thank you for the post!  It really helps.  It looks like the money transaction for the flight is recorded in the red net profit.  Which is 10 silver for the flight.  When you land it should have updated the taxi information but instead is displaying 0 which is wrong.  Hmm.... I will admit this is quite puzzling.  I'll have to review the code.

**Comment by Xruptor** [comment]
Fixed and updated.

**Comment by tanrak** [comment]
Thanks for the update, but there is still a small problem. The taxi fares in the Session section works now but in the Lifetime section still stands "Waiting...".

Edit: I play Wrath classic.

**Comment by Xruptor** [comment]
> Thanks for the update, but there is still a small problem. The taxi fares in the Session section works now but in the Lifetime section still stands "Waiting...".
> 
> Edit: I play Wrath classic.

I'll fix it now in a small patch.  I must have missed that.
