### ISSUE TITLE
Lifetime Total Diff adds Total Earned and Total Spent together instead of subtracting Total Spent from Total Earneed

### ISSUE THREAD

**Issue by ZonisX** [Xruptor/xanGoldMine#4]
Screenshot

![image](https://user-images.githubusercontent.com/2807844/137198368-61d59008-130d-473b-a68f-c8afc217d578.png)

**Comment by Xruptor** [comment]
Try this version and tell me if it fixes by responding here.
[xanGoldMine.zip](https://github.com/Xruptor/xanGoldMine/files/7345835/xanGoldMine.zip)

**Comment by Xruptor** [comment]
I have not heard back yet on this?

**Comment by Xruptor** [comment]
Um it's literally been 22 days now and I haven't heard back from you.  If I don't hear back from you by Sunday, I'm going to close this ticket.

**Comment by Xruptor** [comment]
No user response from ZonisX in 25 days.
